// nullable ? can off that parts
export const partsDisplaySettings = {
  "0_bg": {
    nullable: false,
  },
  "1_face": {
    nullable: false,
  },
  "2_clothes": {
    nullable: false,
  },
  "3_mouth": {
    nullable: false,
  },
  "4_eyes": {
    nullable: false,
  },
  "5_beard": {
    nullable: true,
  },
  "6_eyebrows": {
    nullable: true,
  },
  "7_hair": {
    nullable: true,
  },
  "8_item": {
    nullable: true,
  },
};

export const partsLabels = {
  "0_bg": "背景",
  "1_face": "肌",
  "2_clothes": "服",
  "3_mouth": "口",
  "4_eyes": "目",
  "5_beard": "髭",
  "6_eyebrows": "眉",
  "7_hair": "髪",
  "8_item": "小物",
  "off": "なし",
  "0_bg/1": "無地",
  "0_bg/2": "ストライプ",
  "0_bg/3": "星",
  "0_bg/4": "菱形",
  "1_face/1": "",
  "2_clothes/1": "Tシャツ",
  "2_clothes/2": "タートルネック",
  "2_clothes/3": "パーカー",
  "2_clothes/4": "スーツ",
  "2_clothes/5": "ワイシャツ",
  "3_mouth/1": "口A",
  "3_mouth/2": "口B",
  "3_mouth/3": "口C",
  "3_mouth/4": "口D",
  "3_mouth/5": "口E",
  "4_eyes/1": "目A",
  "4_eyes/2": "目B",
  "4_eyes/3": "目C",
  "4_eyes/4": "目D",
  "4_eyes/5": "目E",
  "4_eyes/6": "目F",
  "4_eyes/7": "目G",
  "4_eyes/8": "目H",
  "5_beard/1": "髭A",
  "5_beard/2": "髭B",
  "5_beard/3": "髭C",
  "5_beard/4": "髭D",
  "5_beard/5": "髭E",
  "6_eyebrows/1": "眉毛A",
  "6_eyebrows/2": "眉毛B",
  "6_eyebrows/3": "眉毛C",
  "6_eyebrows/4": "眉毛D",
  "6_eyebrows/5": "眉毛E",
  "6_eyebrows/6": "眉毛F",
  "6_eyebrows/7": "眉毛G",
  "6_eyebrows/8": "眉毛H",
  "7_hair/1": "髪A",
  "7_hair/2": "髪B",
  "7_hair/3": "髪C",
  "7_hair/4": "髪D",
  "7_hair/5": "髪E",
  "7_hair/6": "髪F",
  "7_hair/7": "髪G",
  "7_hair/8": "髪H",
  "7_hair/9": "髪I",
  "7_hair/10": "髪J",
  "8_item/1": "眼鏡A",
  "8_item/2": "眼鏡B",
  "8_item/3": "サングラスA",
  "8_item/4": "サングラスB",
  "8_item/5": "ほくろA",
  "8_item/6": "ほくろB",
  "8_item/7": "傷",
};
